#Data Keuangan

##Sumber Data
Dataset ini kami ambil dari kaggle (personal-finance-tracker-dataset) : https://www.kaggle.com/datasets/khushikyad001/personal-finance-tracker-dataset?resource=download
<br>

Dimana ini sebagai Data dummy untuk kebutuha Data financial tracker feature

#import Libarary yang dibutuhkan

In [165]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

#LOAD DATA

In [166]:
data_df = pd.read_csv('raw data keuangan.csv')
data_df.head()

,date,user_id,monthly_income,monthly_expense_total,savings_rate,budget_goal,financial_scenario,credit_score,debt_to_income_ratio,loan_payment,...,discretionary_spending,essential_spending,income_type,rent_or_mortgage,category,cash_flow_status,financial_advice_score,financial_stress_level,actual_savings,savings_goal_met
0,2019-01-01,1584,3119.58,3212.07,0.38,3676.11,inflation,721.0,0.56,125.77,...,857.55,1910.85,Freelance,1501.65,Investments,Positive,8.3,Low,0.00,0
1,2019-01-31,1045,3262.44,3732.81,0.10,2607.17,inflation,670.0,0.42,454.19,...,534.51,3165.20,Salary,1603.17,Investments,Positive,22.6,Low,0.00,0
2,2019-03-02,1756,2931.20,3335.58,0.15,3004.14,inflation,691.0,0.24,971.82,...,353.67,1504.56,Freelance,1097.82,Healthcare,Positive,58.8,Low,0.00,0
3,2019-04-01,1724,3506.79,2327.59,0.17,3346.97,normal,717.0,0.16,482.76,...,594.08,1450.72,Freelance,1155.64,Groceries,Positive,74.5,Low,1179.20,0
4,2019-05-01,1600,4606.87,2182.58,0.34,2670.09,inflation,795.0,0.25,263.74,...,556.86,1000.00,Salary,1170.86,Utilities,Negative,38.7,High,2424.29,0

Okey dari dataset personal finance tracker ini, tidak semua kolom akan dipakai dalam data financial treacker feature kami. Kami akan melakukan Feature Selection untuk memiilih kolom kolom yang akan di pakai pada fitur kami yaitu mengenai pemasukan, pengeluaran, dana darurat, rasion hutang/cicilan perbulan

#Feature Selection

##Kolom yang akan dipakai:
- 'Date'
- 'user_id'
- 'monthly_income'
- 'monthly_expense_total'
- 'emergency_fund',
- 'investment_amount',     
- 'debt_to_income_ratio'

In [167]:
feature_kami = [
    'date',
    'user_id',
    'monthly_income',
    'monthly_expense_total',
    'emergency_fund',
    'investment_amount',
    'debt_to_income_ratio'
]

df_feature_kami = data_df[feature_kami].copy()

In [168]:
df_feature_kami.head()

,date,user_id,monthly_income,monthly_expense_total,emergency_fund,investment_amount,debt_to_income_ratio
0,2019-01-01,1584,3119.58,3212.07,510.58,689.22,0.56
1,2019-01-31,1045,3262.44,3732.81,1154.41,360.34,0.42
2,2019-03-02,1756,2931.20,3335.58,1433.02,0.00,0.24
3,2019-04-01,1724,3506.79,2327.59,227.37,182.06,0.16
4,2019-05-01,1600,4606.87,2182.58,589.81,342.78,0.25

#ASSESSING DATA

In [169]:
df_feature_kami.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   3000 non-null   object
 1   user_id                3000 non-null   int64
 2   monthly_income         3000 non-null   float64
 3   monthly_expense_total  3000 non-null   float64
 4   emergency_fund         3000 non-null   float64
 5   investment_amount      3000 non-null   float64
 6   debt_to_income_ratio   3000 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 164.2+ KB

okey harus ubah date (object) ke (datetime),

In [170]:
df_feature_kami.isna().sum()

date                     0
user_id                  0
monthly_income           0
monthly_expense_total    0
emergency_fund           0
investment_amount        0
debt_to_income_ratio     0
dtype: int64

In [171]:
df_feature_kami.duplicated().sum()

np.int64(0)

In [172]:
df_feature_kami.describe()

,user_id,monthly_income,monthly_expense_total,emergency_fund,investment_amount,debt_to_income_ratio
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,1498.699000,4004.267347,3011.682230,1005.349830,400.610493,0.350817
std,287.352782,1000.107096,801.151864,485.780881,235.361273,0.145191
min,1000.000000,685.280000,159.210000,0.000000,0.000000,0.100000
25%,1248.750000,3362.250000,2473.205000,674.012500,234.780000,0.220000
50%,1496.500000,4008.075000,3023.810000,1010.485000,388.075000,0.350000
75%,1749.000000,4659.040000,3555.502500,1337.820000,559.842500,0.480000
max,1999.000000,7407.940000,5853.200000,2585.360000,1292.300000,0.600000

#DATA CLEANING & REPROCESSING

In [173]:
df_clean_data = df_feature_kami.copy()

In [174]:
df_clean_data['date'] = pd.to_datetime(df_clean_data['date'])

In [175]:
df_clean_data['user_id'] = df_clean_data['user_id'].astype(str)

In [176]:
df_clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   3000 non-null   datetime64[ns]
 1   user_id                3000 non-null   object
 2   monthly_income         3000 non-null   float64
 3   monthly_expense_total  3000 non-null   float64
 4   emergency_fund         3000 non-null   float64
 5   investment_amount      3000 non-null   float64
 6   debt_to_income_ratio   3000 non-null   float64
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 164.2+ KB

#FEATURE ENGINEERING

Pembobotan score status kesiapan :
1. Score Dana darurat (MAX) : 40 poin
2. Score Rasio Utang (MAX) : 30 poin
3. Score Cash Flow (MAX) : 30 poin
- Max Score : 100 poin

In [177]:
df_keuangan = df_clean_data.copy()

##Score Dana darurat

In [178]:
df_keuangan['Rasio Dana Darurat'] = (df_keuangan['emergency_fund'] / df_keuangan['monthly_expense_total']).round(2)

# jika rasio >= 6, dapat 40 poin, jika <6 poin dihitung proporsional.
df_keuangan['score_dana_darurat'] = np.where(
    df_keuangan['Rasio Dana Darurat'] >= 6,
    40,
    (df_keuangan['Rasio Dana Darurat'] / 6) * 40
).round(2)

##Score Beban Utang

In [179]:
# semakin kecil utang, semakin baik. jika utang >= 80% dari gaji, skornya 0.
df_keuangan['score_utang'] = np.where(
    df_keuangan['debt_to_income_ratio'] >= 0.8,
    0,
    30 - (df_keuangan['debt_to_income_ratio'] / 0.8 * 30)
).round(2)

##Score Cash Flow

In [180]:
# pemasukan dikurangi Pengeluaran. dan uang sisa harus positif
df_keuangan['cash_flow'] = df_keuangan['monthly_income'] - df_keuangan['monthly_expense_total']

# jika cash flow lebih dari 0, dapat 30 poin. jika minus/pas-pasan, dapat 0 poin.
df_keuangan['score_cashflow'] = np.where(df_keuangan['cash_flow'] > 0, 30, 0).round(2)

##Total Score

In [181]:
df_keuangan['financial_health_score'] = (
    df_keuangan['score_dana_darurat'] +
    df_keuangan['score_utang'] +
    df_keuangan['score_cashflow']
).round(2)

#Status Kesiapan Investasi

Paramater Treshold (ambang batas skor)

In [182]:
def tentukan_status(skor):
    if skor >= 60:
        return 'Siap Investasi'
    elif skor >= 40:
        return 'Perbaiki Dana Darurat dan pelunasan Utang'
    else:
        return 'WARING!!! : Fokus Lunasi Utang & Nabung'

df_keuangan['status_kesiapan'] = df_keuangan['financial_health_score'].apply(tentukan_status)

In [183]:
df_keuangan.head()

,date,user_id,monthly_income,monthly_expense_total,emergency_fund,investment_amount,debt_to_income_ratio,Rasio Dana Darurat,score_dana_darurat,score_utang,cash_flow,score_cashflow,financial_health_score,status_kesiapan
0,2019-01-01,1584,3119.58,3212.07,510.58,689.22,0.56,0.16,1.07,9.00,-92.49,0,10.07,WARING!!! : Fokus Lunasi Utang & Nabung
1,2019-01-31,1045,3262.44,3732.81,1154.41,360.34,0.42,0.31,2.07,14.25,-470.37,0,16.32,WARING!!! : Fokus Lunasi Utang & Nabung
2,2019-03-02,1756,2931.20,3335.58,1433.02,0.00,0.24,0.43,2.87,21.00,-404.38,0,23.87,WARING!!! : Fokus Lunasi Utang & Nabung
3,2019-04-01,1724,3506.79,2327.59,227.37,182.06,0.16,0.10,0.67,24.00,1179.20,30,54.67,Perbaiki Dana Darurat dan pelunasan Utang
4,2019-05-01,1600,4606.87,2182.58,589.81,342.78,0.25,0.27,1.80,20.62,2424.29,30,52.42,Perbaiki Dana Darurat dan pelunasan Utang

In [191]:
df_keuangan.to_csv('data keuangan_clean.csv')

#FILTERING Data keuangan 'Siap Investasi'

#Filtering

In [184]:
df_keuangan_fix = df_keuangan[df_keuangan['status_kesiapan'] == 'Siap Investasi'].copy()

In [185]:
print(f"Jumlah user awal: {len(df_keuangan)}")
print(f"Jumlah user lolos filter (Siap Investasi): {len(df_keuangan_fix)}")

Jumlah user awal: 3000
Jumlah user lolos filter (Siap Investasi): 38

##Feature Selection

In [186]:
kolom_model = ['financial_health_score', 'investment_amount', 'Rasio Dana Darurat']
X = df_keuangan_fix[kolom_model]

##Scalling

In [187]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [188]:
df_for_model = pd.DataFrame(X_scaled, columns=kolom_model, index=df_keuangan_fix.index)

In [189]:
df_for_model.head()

     financial_health_score  investment_amount  Rasio Dana Darurat
67                 1.069605          -0.945184            1.052247
80                 0.444209           0.867691            0.186974
88                -0.132932          -2.070493            0.394152
333               -0.372282           0.662253           -0.519870
365               -0.237165           0.445891           -0.251757

In [190]:
df_for_model.to_csv('data_siap investasi_kmeansModel.csv')